import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Renekin AI",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-24">
      <div className="bg-white/35 backdrop-blur-xl border border-white/50 rounded-2xl p-5 sm:p-8 md:p-12 shadow-xl">
      <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-gray-500 text-sm mb-10">Last updated: March 20, 2026</p>

      <div className="prose prose-gray max-w-none space-y-8 text-gray-600 text-sm leading-relaxed [&_h2]:text-gray-900 [&_strong]:text-gray-900 [&_a]:text-gray-900 [&_a]:underline">
        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the Renekin AI website (renekin.com), the Ghost desktop application,
            or any other services provided by Renekin AI (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;),
            you agree to be bound by these Terms of Service. If you do not agree, do not use our services.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Description of Service</h2>
          <p>
            Renekin AI provides AI-powered tools, including Ghost, a desktop application that offers
            real-time AI assistance. Our services require an internet connection and a user account.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">3. User Accounts</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>You must provide accurate and complete information when creating an account</li>
            <li>You are responsible for maintaining the security of your account credentials</li>
            <li>You must be at least 18 years old to use our services</li>
            <li>One account per person. Do not share accounts.</li>
            <li>We reserve the right to suspend or terminate accounts that violate these terms</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Credits and Payments</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Our services operate on a credit-based system</li>
            <li>New accounts receive 20 free credits upon registration</li>
            <li>Credits are non-transferable and non-refundable unless required by law</li>
            <li>Credits do not expire</li>
            <li>We reserve the right to change pricing at any time, but existing purchased credits will be honored</li>
            <li>Payments are processed securely through Stripe or Razorpay</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>Use the service for any unlawful purpose</li>
            <li>Attempt to reverse engineer, decompile, or disassemble the software</li>
            <li>Share, redistribute, or resell access to the service</li>
            <li>Use automated tools to scrape or abuse the service</li>
            <li>Interfere with or disrupt the service or its infrastructure</li>
            <li>Impersonate another person or entity</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">6. User Responsibility</h2>
          <p>
            You are solely responsible for how you use our services. Ghost is a tool that provides
            AI-generated suggestions. You are responsible for evaluating and using those suggestions
            appropriately. We are not liable for any decisions you make based on AI-generated content.
          </p>
          <p className="mt-2">
            You are responsible for complying with all applicable laws, regulations, and policies
            (including those of any organization or institution you are affiliated with) when using
            our services.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Intellectual Property</h2>
          <p>
            The Renekin AI name, Ghost name, logos, and all software are the intellectual property
            of Renekin AI. You may not use our branding without written permission.
          </p>
          <p className="mt-2">
            Content you submit (resumes, job descriptions) remains yours. We do not claim
            ownership of your content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">8. AI-Generated Content</h2>
          <p>
            AI responses are generated by third-party AI models and may not always be accurate,
            complete, or appropriate. We do not guarantee the quality, accuracy, or suitability
            of AI-generated content. Use your own judgment when acting on AI suggestions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Service Availability</h2>
          <p>
            We strive to maintain high availability but do not guarantee uninterrupted service.
            We may perform maintenance, updates, or experience outages. We are not liable for
            any loss resulting from service unavailability.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Renekin AI shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including but not limited to
            loss of profits, data, or opportunities, arising from your use of our services.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Disclaimer of Warranties</h2>
          <p>
            Our services are provided &quot;as is&quot; and &quot;as available&quot; without warranties
            of any kind, either express or implied, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, or non-infringement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">12. Termination</h2>
          <p>
            We may terminate or suspend your access to our services at any time, with or without cause,
            with or without notice. You may delete your account at any time by contacting us.
            Upon termination, your right to use the service ceases immediately.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">13. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. We will notify users of significant
            changes by posting the updated terms on this page. Continued use of the service after
            changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">14. Governing Law</h2>
          <p>
            These terms shall be governed by and construed in accordance with applicable laws.
            Any disputes arising from these terms shall be resolved through good-faith negotiation
            before pursuing other remedies.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">15. Contact</h2>
          <p>
            If you have any questions about these Terms of Service, contact us at:{" "}
            <a href="mailto:support@renekin.com" className="text-gray-900 hover:text-gray-700 transition">
              support@renekin.com
            </a>
          </p>
        </section>
      </div>
      </div>
    </div>
  );
}
